name: queuey
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # pin_entry_text_field: ^0.1.4
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/Queue-amico.png
     - assets/images/Popup/0.png
     - assets/images/Popup/1.png
     - assets/images/Screens/11-book Q now/index1.png
     - assets/images/Screens/11-book Q now/index2.png
     - assets/images/Screens/11-book Q now/index3.png
     - assets/images/Screens/11-book Q now/index4.png
     - assets/images/Screens/11-book Q now/index5.png
     - assets/images/Screens/11-book Q now/facebook.png
     - assets/images/Screens/11-book Q now/instagram.png
     - assets/images/Screens/11-book Q now/Twitter.png
     - assets/images/Screens/13-Colleges/1.png
     - assets/images/Screens/13-Colleges/2.png
     - assets/images/Screens/13-Colleges/3.png
     - assets/images/Screens/13-Colleges/4.png
     - assets/images/Screens/13-Colleges/5.png
     - assets/images/Screens/13-Colleges/6.png
     - assets/images/Screens/13-Colleges/7.png
     - assets/images/MyAppBar/profile.png
     - assets/images/MyAppBar/list.png
     - assets/images/Screens/5-congrats/accept_img.png
     - assets/images/Screens/5-congrats/ok logo.png
     - assets/images/Screens/12-select destination/1-university.png
     - assets/images/Screens/12-select destination/2-barber.png
     - assets/images/Screens/12-select destination/3-hospital.png
     - assets/images/Screens/12-select destination/4-bank.png
     - assets/images/Screens/12-select destination/5-parking.png
     - assets/images/Screens/12-select destination/6-cafe.png
     - assets/images/Screens/8-signin/face.png
     - assets/images/Screens/8-signin/google.png
     - assets/images/Screens/8-signin/twitter.png
     - assets/images/Screens/19-select department/IT.png
     - assets/images/Screens/19-select department/CS.png
     - assets/images/Screens/19-select department/IS.png
     - assets/images/Screens/19-select department/SW.png
     - assets/images/Screens/19-select department/Bio.png
     - assets/images/Screens/31-Settings/code.png
     - assets/images/Screens/31-Settings/help.png
     - assets/images/Screens/31-Settings/notification.png
     - assets/images/Screens/31-Settings/privacy.png
     - assets/images/Screens/31-Settings/logout.png
     - assets/images/Screens/26-more option/1-About QueueY.png
     - assets/images/Screens/26-more option/2-Report a Problem.png
     - assets/images/Screens/26-more option/3-Rate QueueY.png
     - assets/images/Screens/26-more option/4-Invite your friends.png
     - assets/images/Screens/26-more option/5-Contact us.png
     - assets/images/Screens/14-select service/1-Labs.png
     - assets/images/Screens/14-select service/2-Office hours.png
     - assets/images/Screens/14-select service/3-Student Affairs.png
     - assets/images/Screens/14-select service/4-Library.png
     - assets/images/Screens/14-select service/5-Health Care.png
     - assets/images/Screens/14-select service/6-Payments.png
     - assets/images/Screens/14-select service/7-Events.png
     - assets/images/Screens/7-Success welcome/7-Success welcome.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: OpenSans
       fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
